### ISSUE TITLE
Not working w/ Blender 2.93.5

### ISSUE THREAD

**Issue by Ryuzu** [goweiwen/blender-elu-importer#1]
As the title says, everything went fine until I try to use the latest stable version.
And I got this message.

![blender_hGH5jAb80l](https://user-images.githubusercontent.com/8064354/137163874-05034e16-9c3e-4fbb-b2d6-2639d606a211.png)

**Comment by VantaeGunZ** [comment]
how did you even manage to make it work to begin with ? unless you were using blender 2.49b

**Comment by goweiwen** [comment]
Fixed this, thanks. Tested on Blender 3.1.2
