### ISSUE TITLE
cant import elu/anim. can you help?

### ISSUE THREAD

**Issue by PabloMonfort** [goweiwen/blender-elu-importer#2]

**Comment by PabloMonfort** [comment]
figure out my problem on my way ty.

**Comment by superswan** [comment]
What is the solution, I cannot import .ani extension

**Comment by PabloMonfort** [comment]
oh a big trip, i used the old blender where i can see animations then i save as blender file then i open in new blender then i export the anim as dae o collada cant remember well some of them dosnt export well but can be fixed seems some rotation problem .

**Comment by superswan** [comment]
> oh a big trip, i used the old blender where i can see animations then i save as blender file then i open in new blender then i export the anim as dae o collada cant remember well some of them dosnt export well but can be fixed seems some rotation problem .

thank you that's a good idea. i am working on updating the addon to import .ani

it seems this addon does not correctly create armature like the previous addons for 2.49
